[package]
name = "cargo-propagate-features"
description = "Cargo subcommand to automatically propagate workspace crate features to dependencies"
version = "0.0.6"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["Jacobus Geluk <jacobus@dataroad.com>"]
repository = "https://github.com/legra-ai/cargo-propagate-features"
documentation = "https://docs.rs/cargo-propagate-features"
homepage = "https://github.com/legra-ai/cargo-propagate-features"
rust-version = "1.94.1"
readme = "README.md"
keywords = ["cargo", "features", "workspace", "cli"]
categories = ["command-line-utilities", "development-tools"]
publish = true

exclude = [
    ".cargo/",
    ".cargo-husky/",
    ".clippy.toml",
    ".cursor/",
    ".github/",
    ".gitignore",
    ".rust-toolchain.toml",
    ".vscode/",
    "cog.toml",
    "rustfmt.toml",
    "scripts/",
]

[[bin]]
name = "cargo-propagate-features"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.6", default-features = false, features = [
    "derive",
    "env",
    "std",
] }
serde = { version = "1", features = ["derive"] }
toml_edit = "=0.25.13"
cargo-plugin-utils = "0.0.12"

[build-dependencies]
cargo-version-info = "0.0.21"
rhusky = "0.0.6"

[dev-dependencies]
tempfile = "3"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }.{ archive-format }"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "zip"
